import("//build/ohos.gni")
import("//build/ohos_var.gni")
import("//foundation/communication/bluetooth/bluetooth.gni")

group("bluetooth_group") {
    deps =[
        "//foundation/communication/bluetooth/frameworks/inner:btframework",
          "//foundation/communication/bluetooth/frameworks/inner:btcommon",
          "//foundation/communication/bluetooth/frameworks/js/napi:bluetooth_napi",
          "//foundation/communication/bluetooth/frameworks/c_api:bluetooth_ndk",
          "//foundation/communication/bluetooth/frameworks/cj:bluetooth_ffi",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_a2dp:bluetoothA2dp_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_access:bluetoothAccess_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_baseProfile:bluetoothBaseProfile_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_ble:bluetoothBle_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_connection:bluetoothConnection_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_constant:bluetoothConstant_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_hfp:bluetoothHfp_taihe",
          "//foundation/communication/bluetooth/frameworks/ets/taihe/bluetooth_hid:bluetoothHid_taihe",
          "//foundation/communication/bluetooth/frameworks/js/napi:bluetooth_override_napi",
          "//foundation/communication/bluetooth/frameworks/inner:bluetooth_override_framework",
          "//foundation/communication/bluetooth/services/bluetooth/btchr:btchr",
          "//foundation/communication/bluetooth/services/bluetooth/common:btservice_common",
          "//foundation/communication/bluetooth/services/bluetooth/hardware:bluetooth_hdi_adapter",
          "//foundation/communication/bluetooth/config:feature_flags_static",
          "//foundation/communication/bluetooth/tools/ohos-bluetoothTool:ohos-bluetoothTool",
          "//foundation/communication/bluetooth/bluetooth_ui:bluetooth_hap",
          "//foundation/communication/bluetooth/sa_profile:communication_bluetooth_sa_profile",
          "//foundation/communication/bluetooth/services/bluetooth/server:bluetooth_server",
          "//foundation/communication/bluetooth/services/bluetooth/service:btavrcp_media",
          "//foundation/communication/bluetooth/services/bluetooth/service:btfast_scan",
          "//foundation/communication/bluetooth/services/bluetooth/service/src/pan:btpan",
          "//foundation/communication/bluetooth/services/bluetooth/service:btpbap_pse",
          "//foundation/communication/bluetooth/services/bluetooth/service:btmap_mse",
          "//foundation/communication/bluetooth/services/bluetooth/service:btopp",
          "//foundation/communication/bluetooth/services/bluetooth/service:bthearing_aid_impl",
          "//foundation/communication/bluetooth/idl:bluetooth_override_idl",
          "//foundation/communication/bluetooth/services/bluetooth/service:bthiddevice",
          "//foundation/communication/bluetooth/services/bluetooth/service:btbas"
    ]
}