import("//build/ohos.gni")
import("//build/ohos_var.gni")
import("//foundation/communication/bluetooth/bluetooth.gni")

group("bluetooth_group") {
    deps =[
          "//foundation/communication/bluetooth/services/bluetooth/btchr:btchr",
          "//foundation/communication/bluetooth/services/bluetooth/common:btservice_common",
          "//foundation/communication/bluetooth/services/bluetooth/hardware:bluetooth_hdi_adapter",
          "//foundation/communication/bluetooth/config:feature_flags_static",
          "//foundation/communication/bluetooth/sa_profile:communication_bluetooth_sa_profile",
          "//foundation/communication/bluetooth/services/bluetooth/server:bluetooth_server",
          "//foundation/communication/bluetooth/services/bluetooth/service:btavrcp_media",
          "//foundation/communication/bluetooth/services/bluetooth/service:btfast_scan",
          "//foundation/communication/bluetooth/services/bluetooth/service/src/pan:btpan",
          "//foundation/communication/bluetooth/services/bluetooth/service:btpbap_pse",
          "//foundation/communication/bluetooth/services/bluetooth/service:btmap_mse",
          "//foundation/communication/bluetooth/services/bluetooth/service:btopp",
          "//foundation/communication/bluetooth/services/bluetooth/service:bthearing_aid_impl",
          "//foundation/communication/bluetooth/idl:bluetooth_override_idl",
          "//foundation/communication/bluetooth/services/bluetooth/service:bthiddevice",
          "//foundation/communication/bluetooth/services/bluetooth/service:btbas"
    ]
}