# Copyright (C) 2021-2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/ohos_var.gni")
import("//foundation/communication/bluetooth/bluetooth.gni")

BT_ROOT = "//foundation/communication/bluetooth/services/bluetooth"

bluetooth_server_deps = [
  "$BT_ROOT/btchr:btchr",
  "$BT_ROOT/common:btservice_common",
  "$BT_ROOT/etc/init:etc",
  "$BT_ROOT/etc/param:etc",
  "$BT_ROOT/ipc:bt_service_ipc",
  "$BT_ROOT/service:btservice",
  "//foundation/communication/bluetooth/frameworks/inner:btcommon",
]

if (bluetooth_hearingaid_feature_switch) {
  IDL_ROOT = "//foundation/communication/bluetooth/idl"
  bluetooth_server_deps += ["$IDL_ROOT/hearingaid:libbluetooth_hearingaid_interface_stub",]
}

bluetooth_server_external_deps = [
  "access_token:libaccesstoken_sdk",
  "c_utils:utils",
  "eventhandler:libeventhandler",
  "hicollie:libhicollie",
  "hisysevent:libhisysevent",
  "hitrace:hitrace_meter",
  "hilog:libhilog",
  "ipc:ipc_single",
  "safwk:system_ability_fwk",
  "samgr:samgr_proxy",
  "init:libbegetutil",
  "init:libbeget_proxy",
  "preferences:native_preferences",
  "wifi:wifi_sdk",
  "common_event_service:cesfwk_innerkits",
]
if (bluetooth_ffrt_enable) {
  bluetooth_server_external_deps += [ "ffrt:libffrt" ]
}
if (bluetooth_resourceschedule) {
  bluetooth_server_external_deps += [ "resource_schedule_service:ressched_client" ]
}

bluetooth_server_sources = [
  "src/ble_scanner_state_machine.cpp",
  "src/bluetooth_a2dp_source_server.cpp",
  "src/bluetooth_avrcp_tg_server.cpp",
  "src/bluetooth_ble_advertiser_server.cpp",
  "src/bluetooth_ble_central_manager_server.cpp",
  "src/bluetooth_ble_filter_matcher.cpp",
  "src/bluetooth_gatt_client_server.cpp",
  "src/bluetooth_gatt_server_server.cpp",
  "src/bluetooth_hfp_ag_server.cpp",
  "src/bluetooth_hid_host_server.cpp",
  "src/bluetooth_hitrace.cpp",
  "src/bluetooth_host_dumper.cpp",
  "src/bluetooth_host_server.cpp",
  "src/bluetooth_socket_server.cpp",
  "src/bluetooth_utils_server.cpp",
  "src/bluetooth_device_manager.cpp",
  "src/bluetooth_audio_manager_server.cpp",
  "src/bluetooth_connection_server.cpp",
  "src/bluetooth_observer_application_container.cpp",
  "src/bluetooth_svc_cmd.cpp",
]
if (bluetooth_hfp_hf_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_hfp_hf_server.cpp",]
}
if (bluetooth_a2dp_sink_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_a2dp_sink_server.cpp",]
}
if (bluetooth_pan_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_pan_server.cpp"]
}
if (bluetooth_avrcp_ct_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_avrcp_ct_server.cpp",]
}
if (bluetooth_pbap_pse_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_pbap_pse_server.cpp",]
}
if (bluetooth_map_mse_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_map_mse_server.cpp",]
}
if (bluetooth_opp_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_opp_server.cpp",]
}
if (bluetooth_hearingaid_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_hearingaid_server.cpp",]
}
if (bluetooth_contexthub_ble) {
  bluetooth_server_sources += ["src/bluetooth_sensorhub_collaboration.cpp",]
}

if (bluetooth_hid_device_feature_switch) {
  bluetooth_server_sources += ["src/bluetooth_hid_device_server.cpp",]
}

if (bluetooth_bas_feature) {
  bluetooth_server_sources += ["src/bluetooth_bas_server.cpp",]
}

config("bluetooth_server_config") {
  include_dirs = [
    "include",
    "$BT_ROOT/btchr/include",
    "$BT_ROOT/common",
    "$BT_ROOT/ipc/include",
    "$BT_ROOT/service/include",
    "$BT_ROOT/service/src",
    "$BT_ROOT/service/src/base",
    "$BT_ROOT/service/src/ble",
    "$BT_ROOT/service/src/classic",
    "$BT_ROOT/service/src/common",
    "$BT_ROOT/service/src/util",
    "$BT_ROOT/service/src/permission",
    "$BT_ROOT/service/src/bluetooth_audio_manager",
    "//foundation/communication/bluetooth/frameworks/inner/include",
  ]

  cflags_cc = [
    "-Os",
    "-fno-rtti",
    "-fno-exceptions",
    "-fdata-sections",
    "-ffunction-sections",
    "-fno-unwind-tables",
    "-fno-asynchronous-unwind-tables",
    "-fno-merge-all-constants",
    "-flto",
    "-Wno-format",
  ]
}

#################################### bluetooth_server ########################################
ohos_shared_library("bluetooth_server") {
  # Used to control the export of dynamic library symbols.
  version_script = "libbluetooth_server_version_script.txt"
  # CFI
  branch_protector_ret = "pac_ret"  # Enable PAC CFI
  # stack_protector_ret = true
  sanitize = {
      cfi = true                            # Enable/disable control flow integrity detection
      boundary_sanitize = true               # Enable boundary san detection
      cfi_cross_dso = true                   # Cross-SO CFI Checks
      integer_overflow = true                # Enable integer overflow detection
      ubsan = true                           # Enable some Ubsan options
      debug = false
  }
  configs = [
    ":bluetooth_server_config",
    "${bluetooth_config_path}:feature_flags",
  ]
  defines = []
  if (bluetooth_bt_mcu_proxy_enable) {
    defines += ["BT_MCU_PROXY_ENABLE"]
  }
  sources = bluetooth_server_sources
  deps = bluetooth_server_deps
  external_deps = bluetooth_server_external_deps

  part_name = "bluetooth"
  subsystem_name = "communication"
}

#################################### bluetooth_server_static ###################################
# Only used for unitest
ohos_static_library("bluetooth_server_static") {
  configs = [
    ":bluetooth_server_config",
    "${bluetooth_config_path}:feature_flags",
  ]
  sanitize = {
    cfi = true                            # Enable/disable control flow integrity detection
    cfi_cross_dso = true                   # Cross-SO CFI Checks
    debug = false
    blocklist = "libbluetooth_server_static_blocklist.txt"
  }
  sources = bluetooth_server_sources
  deps = bluetooth_server_deps
  external_deps = bluetooth_server_external_deps

  part_name = "bluetooth"
  subsystem_name = "communication"
}
