/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Stub of the removed stack layer HAL interface (hardware/bluetooth.h).
 * The stack library is dlopened at runtime via hal_util; a null interface is
 * tolerated by the service layer, only the shape of the entry point matters.
 */

#ifndef HARDWARE_BLUETOOTH_H
#define HARDWARE_BLUETOOTH_H

#include <cstddef>
#include <cstdint>

#include "bt_types.h"

/* Profile identifiers passed to BtInterface::GetProfileInterface; the
 * values mirror the removed stack layer HAL (hardware/bluetooth.h). */
#define BT_PROFILE_HANDSFREE_ID "handsfree"
#define BT_PROFILE_HANDSFREE_CLIENT_ID "handsfree_client"
#define BT_PROFILE_ADVANCED_AUDIO_ID "a2dp"
#define BT_PROFILE_ADVANCED_AUDIO_SINK_ID "a2dp_sink"
#define BT_PROFILE_SOCKETS_ID "socket"
#define BT_PROFILE_HIDHOST_ID "hidhost"
#define BT_PROFILE_HIDDEV_ID "hiddev"
#define BT_PROFILE_PAN_ID "pan"
#define BT_PROFILE_SDP_CLIENT_ID "sdp"
#define BT_PROFILE_GATT_ID "gatt"
#define BT_PROFILE_AV_RC_CTRL_ID "avrcp_ctrl"
#define BT_PROFILE_HEARING_AID_ID "hearing_aid"

/* OOB data layout sizes referenced by the service layer when validating the
 * local OOB data generated by the stack. */
#define OOB_ADDRESS_SIZE 7
#define OOB_C_SIZE 16
#define OOB_R_SIZE 16
#define OOB_NAME_MAX_SIZE 256

/* Callbacks registered by the service layer via BtInterface::init; the
 * signatures mirror the AdapterManager static callbacks. */
struct BtCallbacks {
    size_t size;
    void (*adapterStateChangedCb)(BtState state);
    void (*adapterPropertiesCb)(BtStackStatus status, int numProperties, BtProperty *properties);
    void (*remoteDevicePropertiesCb)(BtStackStatus status, OHOS::bluetooth::RawAddress *bdAddr, int numProperties,
        BtProperty *properties);
    void (*deviceFoundCb)(int numProperties, BtProperty *properties);
    void (*discoveryStateChangedCb)(BtDiscoveryState state);
    void (*pinRequestCb)(OHOS::bluetooth::RawAddress *remoteBdAddr, BtBdname *bdName, uint32_t cod,
        bool min16Digit);
    void (*sspRequestCb)(OHOS::bluetooth::RawAddress *remoteBdAddr, BtBdname *bdName, uint32_t cod,
        BtSspVariant pairingVariant, uint32_t passKey);
    void (*bondStateChangedCb)(BtStackStatus status, OHOS::bluetooth::RawAddress *remoteBdAddr,
        BtBondState state);
    void (*aclStateChangedCb)(BtStackStatus status, OHOS::bluetooth::RawAddress *remoteBdAddr,
        BtAclState state, BtHciErrorCode hciReason, BtTransport linkType);
    void (*threadEvtCb)(BtCbThreadEvt evt);
    void (*dutModeRecvCb)(uint16_t opcode, uint8_t *buf, uint8_t len);
    void (*energyInfoCb)(BtActivityEnergyInfo *energyInfo, BtUidTraffic *uidData);
    void (*generateLocalOobDataCb)(BtTransport transport, BtStackOobData oobData);
    void (*sensingStateChangedCb)(uint8_t eventId, BtSensingInfo *info);
};

/* OS callouts optionally registered via SetOsCallouts. */
struct BtOsCallouts {
    size_t size;
    int (*setWakeAlarm)(uint64_t alarmTimeMillis, bool shouldWake);
    int (*acquireWakeLock)(const char *lockName);
    int (*releaseWakeLock)(const char *lockName);
};

/* Forward declaration of the stubbed AVRCP service interface so that the
 * GetAvrcpService entry point can return it directly (service code assigns
 * the result without a cast). */
namespace bluetooth {
namespace avrcp {
class ServiceInterface;
}  // namespace avrcp
}  // namespace bluetooth

struct BtInterface {
    size_t size;
    int (*init)(BtCallbacks *callbacks, bool startRestricted, bool isCommonCriteriaMode,
        int configCompareResult, void *reserved, bool isAtv);
    int (*enable)(void);
    int (*disable)(void);
    void (*cleanup)(void);
    int (*setOsCallouts)(void *callouts);
    const void *(*getProfileInterface)(const char *profileId);
    bluetooth::avrcp::ServiceInterface *(*getAvrcpService)(void);
    int (*getRemoteServices)(OHOS::bluetooth::RawAddress *bdAddr);
    int (*enableBluetoothHighpower)(bool enable);
    int (*enableFastScan)(bool isEnable);
    int (*setFastScan)(int level);
    int (*sendAntennaStatusMsg)(bool isFixed);
    int (*sendBleScanMsg)(bool isStarted);
    int (*configClear)(void);
    int (*createBond)(const OHOS::bluetooth::RawAddress *bdAddr, int transport);
    int (*createBondOutOfBand)(const OHOS::bluetooth::RawAddress *bdAddr, int transport,
        const BtStackOobData *p192Data, const BtStackOobData *p256Data);
    int (*cancelBond)(const OHOS::bluetooth::RawAddress *bdAddr);
    int (*removeBond)(const OHOS::bluetooth::RawAddress *bdAddr);
    int (*pinReply)(const OHOS::bluetooth::RawAddress *bdAddr, bool accept, uint8_t pinLen,
        BtPinCode *pinCode);
    int (*sspReply)(const OHOS::bluetooth::RawAddress *bdAddr, BtSspVariant variant, bool accept,
        uint32_t passkey);
    int (*getRemoteDeviceProperties)(OHOS::bluetooth::RawAddress *bdAddr);
    int (*getRemoteDeviceProperty)(OHOS::bluetooth::RawAddress *bdAddr, BtPropertyType type);
    int (*setRemoteDeviceProperty)(OHOS::bluetooth::RawAddress *bdAddr, const BtProperty *property);
    int (*setAdapterProperty)(BtProperty *property);
    int (*startDiscovery)(void);
    int (*cancelDiscovery)(void);
    int (*generateLocalOobData)(int transport);
    void (*createAclConnection)(OHOS::bluetooth::RawAddress *addr);
    /* Ranging antenna switch support consumed by BleRangeImpl; the callback
     * reports the MAC/antenna ids selected by the stack. */
    int (*registerRangingAntSwitchCallback)(void (*callback)(uint8_t macID, uint8_t antID));
    void (*unregisterRangingAntSwitchCallback)(void);
    void (*sendBleAdvStartMsg)(uint32_t mac, uint32_t ant);
    void (*sendBleAdvStopMsg)(void);
    void (*sendAntennaInfoQueryMsg)(void);
};

#endif  // HARDWARE_BLUETOOTH_H
