/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Stub of the removed stack layer HAL interface (hardware/bluetooth.h).
 * The stack library is dlopened at runtime via hal_util; a null interface is
 * tolerated by the service layer, only the shape of the entry point matters.
 */

#ifndef HARDWARE_BLUETOOTH_H
#define HARDWARE_BLUETOOTH_H

#include <cstddef>
#include <cstdint>

#include "bt_types.h"

/* Profile identifiers passed to bt_interface_t::get_profile_interface; the
 * values mirror the removed stack layer HAL (hardware/bluetooth.h). */
#define BT_PROFILE_HANDSFREE_ID "handsfree"
#define BT_PROFILE_HANDSFREE_CLIENT_ID "handsfree_client"
#define BT_PROFILE_ADVANCED_AUDIO_ID "a2dp"
#define BT_PROFILE_ADVANCED_AUDIO_SINK_ID "a2dp_sink"
#define BT_PROFILE_SOCKETS_ID "socket"
#define BT_PROFILE_HIDHOST_ID "hidhost"
#define BT_PROFILE_HIDDEV_ID "hiddev"
#define BT_PROFILE_PAN_ID "pan"
#define BT_PROFILE_SDP_CLIENT_ID "sdp"
#define BT_PROFILE_GATT_ID "gatt"
#define BT_PROFILE_AV_RC_CTRL_ID "avrcp_ctrl"
#define BT_PROFILE_HEARING_AID_ID "hearing_aid"

/* OOB data layout sizes referenced by the service layer when validating the
 * local OOB data generated by the stack. */
#define OOB_ADDRESS_SIZE 7
#define OOB_C_SIZE 16
#define OOB_R_SIZE 16
#define OOB_NAME_MAX_SIZE 256

/* Callbacks registered by the service layer via bt_interface_t::init; the
 * signatures mirror the AdapterManager static callbacks. */
typedef struct {
    size_t size;
    void (*adapter_state_changed_cb)(bt_state_t state);
    void (*adapter_properties_cb)(bt_status_t status, int num_properties, bt_property_t* properties);
    void (*remote_device_properties_cb)(bt_status_t status, RawAddress* bd_addr, int num_properties,
        bt_property_t* properties);
    void (*device_found_cb)(int num_properties, bt_property_t* properties);
    void (*discovery_state_changed_cb)(bt_discovery_state_t state);
    void (*pin_request_cb)(RawAddress* remote_bd_addr, bt_bdname_t* bd_name, uint32_t cod, bool min_16_digit);
    void (*ssp_request_cb)(RawAddress* remote_bd_addr, bt_bdname_t* bd_name, uint32_t cod,
        bt_ssp_variant_t pairing_variant, uint32_t pass_key);
    void (*bond_state_changed_cb)(bt_status_t status, RawAddress* remote_bd_addr, bt_bond_state_t state);
    void (*acl_state_changed_cb)(bt_status_t status, RawAddress* remote_bd_addr, bt_acl_state_t state,
        bt_hci_error_code_t hci_reason, tBT_TRANSPORT link_type);
    void (*thread_evt_cb)(bt_cb_thread_evt evt);
    void (*dut_mode_recv_cb)(uint16_t opcode, uint8_t* buf, uint8_t len);
    void (*energy_info_cb)(bt_activity_energy_info* energy_info, bt_uid_traffic_t* uid_data);
    void (*generate_local_oob_data_cb)(tBT_TRANSPORT transport, bt_oob_data_t oob_data);
    void (*sensing_state_changed_cb)(uint8_t event_id, bt_sensing_info_t* info);
} bt_callbacks_t;

/* OS callouts optionally registered via set_os_callouts. */
typedef struct {
    size_t size;
    int (*set_wake_alarm)(uint64_t alarm_time_millis, bool should_wake);
    int (*acquire_wake_lock)(const char* lock_name);
    int (*release_wake_lock)(const char* lock_name);
} bt_os_callouts_t;

/* Forward declaration of the stubbed AVRCP service interface so that the
 * get_avrcp_service entry point can return it directly (service code assigns
 * the result without a cast). */
namespace bluetooth {
namespace avrcp {
class ServiceInterface;
}  // namespace avrcp
}  // namespace bluetooth

typedef struct {
    size_t size;
    int (*init)(...);
    int (*enable)(...);
    int (*disable)(...);
    void (*cleanup)(void);
    int (*set_os_callouts)(void *callouts);
    const void *(*get_profile_interface)(const char *profileId);
    bluetooth::avrcp::ServiceInterface *(*get_avrcp_service)(void);
    int (*get_remote_services)(...);
    int (*enable_bluetooth_highpower)(...);
    int (*enable_fast_scan)(...);
    int (*setFastScan)(...);
    int (*send_antenna_status_msg)(...);
    int (*send_ble_scan_msg)(...);
    int (*config_clear)(...);
    int (*create_bond)(...);
    int (*create_bond_out_of_band)(...);
    int (*cancel_bond)(...);
    int (*remove_bond)(...);
    int (*pin_reply)(...);
    int (*ssp_reply)(...);
    int (*get_remote_device_properties)(...);
    int (*get_remote_device_property)(...);
    int (*set_remote_device_property)(...);
    int (*set_adapter_property)(...);
    int (*start_discovery)(...);
    int (*cancel_discovery)(...);
    int (*generate_local_oob_data)(...);
    void (*create_acl_connection)(RawAddress *addr);
    /* Ranging antenna switch support consumed by BleRangeImpl; the callback
     * reports the MAC/antenna ids selected by the stack. */
    int (*register_ranging_ant_switch_callback)(void (*callback)(uint8_t macID, uint8_t antID));
    void (*unregister_ranging_ant_switch_callback)(void);
    void (*sendbleadvstartmsg)(uint32_t mac, uint32_t ant);
    void (*sendbleadvstopmsg)(void);
    void (*send_antenna_info_query_msg)(void);
} bt_interface_t;

#endif  // HARDWARE_BLUETOOTH_H
